### ISSUE TITLE
Overall

### ISSUE THREAD

**Issue by Axkaban** [scgray67/prj-rev-bwfs-dasmoto#3]
Great Job! everything is as requested. try practicing ids, comments, grouping elements for same css properties, as you’re in a very good path! 

As an extra challenge. give those pictures an opacity and change it with the pseudo-class `:hover` 

Hope I get to see what you’ll make next! Good luck and happy holidays!

**Comment by scgray67** [comment]
Thank you for the comments. Working on commenting and classes vs ids now.
