### ISSUE TITLE
incorrect linking to css 

### ISSUE THREAD

**Issue by ad3429** [scgray67/prj-rev-bwfs-dasmoto#4]
https://github.com/scgray67/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/index.html#L6

It seems you incorrectly linked to your CSS by linking to a local file on your computer. The correct way to link would be:

<img width="409" alt="screen shot 2017-12-28 at 4 03 12 pm" src="https://user-images.githubusercontent.com/25671399/34423232-9dd88c76-ebe8-11e7-9895-6368e0d2451d.png">

**Comment by scgray67** [comment]
Thanks and yes. I should have caught this prior to uploading. This has been corrected.
